databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "0"
- key: DJANGO_ALLOWED_HOST
  scope: RUN_AND_BUILD_TIME
  value: try-django-3-2-g7hj7.ondigitalocean.app
- key: DJANGO_SUPERUSER_EMAIL
  scope: RUN_AND_BUILD_TIME
  value: hello@teamcfe.com
- key: DJANGO_SUPERUSER_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: cfe
- key: DJANGO_SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:O4AGkmcqHr7K93v8psaNTowk3gYilqhl:8U3LKjCi/WGpI4fO/82ltGAEh2E/KK2UDS27A0wiDkLRK2pu+CuaszHyUxJxkGgMzeHIvRkrv3+nGaG768wLh96M]
- key: DJANGO_SUPERUSER_PASSWORD
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:eI5fSSqZkfLZJCodTkGOPv53aUkW3ksT:4GzeVJ5YSuPKyUhT32q87/2DftIVqliWl30c6jZWWwTMen393vhkxj0JeD5rhjPI42uWZccLMFGNr8XWwb1GXr3N]
- key: POSTGRES_DB
  scope: RUN_AND_BUILD_TIME
  value: ${db.DATABASE}
- key: POSTGRES_HOST
  scope: RUN_AND_BUILD_TIME
  value: ${db.HOSTNAME}
- key: POSTGRES_USER
  scope: RUN_AND_BUILD_TIME
  value: ${db.USERNAME}
- key: POSTGRES_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: ${db.PASSWORD}
- key: POSTGRES_PORT
  scope: RUN_AND_BUILD_TIME
  value: ${db.PORT}
- key: AWS_ACCESS_KEY_ID
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:8tUA4iPz6RXmTBE5JWGCuuVjftuzAUxs:FfHvzQv7V3Wi4lqNX14DLrqPFGrNlNHAXarmTjSBH9pAt9YJ]
- key: AWS_SECRET_ACCESS_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:kfGInyKA+O218USZE4tqrS90hAOUWNvY:3oTK1Q7GSLEYRzBqnhH0IiTNiDsVu/fZcToRtNfSI65I8urcKdbgd4zGirJ1bb7/89SbQjO2teq0zLI=]
- key: AWS_STORAGE_BUCKET_NAME
  scope: RUN_AND_BUILD_TIME
  value: trydjango3
jobs:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  git:
    repo_clone_url: https://www.github.com/codingforentrepreneurs/Try-Django-3.2
    branch: production-3
  instance_count: 1
  instance_size_slug: basic-xxs
  kind: PRE_DEPLOY
  name: django-migrate-job
  run_command: python manage.py migrate --noinput
  source_dir: /
name: try-django-3-2
region: nyc
services:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  git:
    repo_clone_url: https://www.github.com/codingforentrepreneurs/Try-Django-3.2
    branch: production-3
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: try-django-3-2
  routes:
  - path: /
  run_command: gunicorn --worker-tmp-dir /dev/shm trydjango.wsgi
  source_dir: /